version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run build
    volumes:
      - ./frontend:/app
      - ./frontend/dist:/app/dist
    # Elimina el contenedor después de la build
    deploy:
      replicas: 0

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./backend:/app
      - ./frontend/dist:/app/dist # Monta la carpeta de build en el servidor Express
    ports:
      - "4000:4000"
    depends_on:
      - frontend
