version: '3'

services:
  client:
    container_name: docker-client
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: npm run build
    volumes:
      - ./client:/app
      - ./client/dist:/app/dist

  server:
    container_name: docker-server
    build:
      context: ./server
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./server:/app
      - ./client/dist:/app/dist # Monta la carpeta de build en el servidor Express
    ports:
      - "4000:4000"
    depends_on:
      - client
