version: '3.8' # Versi贸n de Docker Compose

services:
  app: # Nombre del servicio
    image: 'app4' # Nombre de la imagen
    build: # Configuraci贸n de construcci贸n
      context: . # Ruta al directorio donde se encuentra tu Dockerfile
      dockerfile: Dockerfile # Nombre del Dockerfile (opcional si es "Dockerfile")
    ports:
      - '4000:4000' # Mapeo de puertos
    volumes:
      - .:/app # Monta el directorio actual en /app del contenedor
    environment:
      PORT: 4000
      # Cambia a `mongodb://` en lugar de `mongodb+srv://` y especifica el puerto 27017
      MONGO_URI: mongodb+srv://AgustinM12:24879156@combodb.uusbhhs.mongodb.net/bd
      ALLOWED_IP: 172.18.0.1
      IP_TOKEN: a631f41522aa77
      JWT_SECRET: 17gisusbgklsdguiwn
    command: ['npm', 'run', 'start'] # Comando para ejecutar tu aplicaci贸n
    dns:
      - 8.8.8.8 # Google DNS
      - 1.1.1.1 # Cloudflare DNS
